apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: vc-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-svc
  template:
    metadata:
      labels:
        app: vc-svc
        version: v1
    spec:
      containers:
        - name: vc-svc
          env:
          - name: GOPATH
            value: /go:$GOPATH
          - name: GO_ENV
            value: default
          - name: GIN_MODE
            value: release
          command: [
            "/go/src/vc.svc/vc-svc",
            # "--selector=static",
            # “--client=grpc”,
            # "--server=grpc",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001",
            # "--server_version=v1",
            "--registry=kubernetes"
          ]
          image: zeqi/vc-svc:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: vc-svc
  namespace: default
  labels:
    app: vc-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: tcp
  selector:
    app: vc-svc
    version: v1